name       : libfilteraudio
version    : 0.1
release    : 2
source     :
    - http://stroblindustries.com/solus-tarballs/libfilteraudio.tar.bz2 : 0229165ef4069abfecc152eb90809593af876b1f5ba6a034287b7c49dbb3cfd7
license    : BSD-3
component  : multimedia.library
summary    : Lightweight audio filtering library made from webrtc code.
description: |
    Lightweight audio filtering library made from webrtc code.
build      : |
    %make
install    : |
    %make_install
    mv $installdir/usr/local/* $installdir/usr/
    mv $installdir/usr/lib $installdir/%libdir%
    rm $installdir/%libdir%/*.a
    rmdir $installdir/usr/local
